export 'movies/movie_providers.dart';
export 'movies/movie_repository_provider.dart';
export 'movies/movie_slideshow_provider.dart';
export 'init_loader/init_loader_provider.dart';
export 'details/movie_details_provider.dart';
export 'actors/actors_provider.dart';
export 'actors/actors_repository_provider.dart';
export 'search/search_movie_provider.dart';
export 'storage/local_storage_provider.dart';
